### PR TITLE
Rebase to remove invalid auth_token

### PR DESCRIPTION
**Pull request by balaji-viswanathan**
ADO WI: https://msrceng.visualstudio.com/VulnReports/_workitems/edit/216726

We have 2 commits in `master` branch which has auth_token exposed:
https://github.com/microsoft/ObjectStoreProvider/commit/5e124536dfab81f6b2297c56a005af699b0d0adf
https://github.com/microsoft/ObjectStoreProvider/commit/93b2337e3344541bbc20bd39c760dc2c393c0bf3

These tokens are invalidated and we also need to remove the commits (that added these tokens) from commit history.

Here's a PR which is rebased to remove the commits from commit history. (I don't think I have access to force push to `master` branch, so here's the PR)

We can see that commits which had auth_token exposed in npmrc doesn't exist in this branch:
https://github.com/microsoft/ObjectStoreProvider/commits/user/bviswanathan/remove_auth_token/.npmrc

### CODE REVIEW

**Comment by thomastay** [comment]
Do you know why the commits here look out of order?
Also, will this erase our commit history?

**Comment by balaji-viswanathan** [comment]
> Do you know why the commits here look out of order? 

Here's the commit history of `master` branch:

image

This PR won't have two commits marked in green. We can see the history appearing in this PR starting with commit marked in red, in the same order. Not sure what you mean by "out of order".

> Also, will this erase our commit history?

Yes, will delete those commits and the commit history from that point onwards will be modified.

**Comment by thomastay** [comment]
can you check that the tests build with your current changes

**Comment by thomastay** [comment]
run `yarn ci:test`

**Comment by balaji-viswanathan** [comment]
> run `yarn ci:test`

Yes, succeeds in PR build: https://github.com/microsoft/ObjectStoreProvider/actions/runs/10374350179/job/28721557970?pr=58

**Review by eliranek1 — APPROVED** [review]

**Pull request merged**
